### ISSUE TITLE
Java command not found

### ISSUE THREAD

**Issue by prohand** [Zimbra-Community/mailing-lists#1]
Hello,

First of all thank you for the script :)
I have a problem with the script.
When I validate the configuration I receive this error message:
```

mesg: ttyname failed: Inappropriate ioctl for device
/usr/local/sbin/process_mailinglists: line 3: java: command not found
```

Thank you in advance for your assistance

**Comment by ghost** [comment]
Please re-run the installer to try again.

Thanks!

**Comment by prohand** [comment]
Thanks,

I have an another error.
I open a new ticket
