### ISSUE TITLE
What does the milter recipe do?

### ISSUE THREAD

**Issue by cdhassell** [Zimbra-Community/mailing-lists#6]
Hi, thank you for this project!  I am planning to install the mailing-lists code to allow people to subscribe to our mailing lists from a web page.  However I see the wiki page about setting mailing list headers with milter, and I am not sure what problem it is trying to solve.  It says, "By default Zimbra distribution lists do not set appropriate e-mail headers."  What is wrong with the headers exactly?  I am trying to determine whether we can live with the problem, since the solution in the wiki is for Red Hat and apparently does not work for Ubuntu. Thanks.

**Comment by ghost** [comment]
Without the Milter you can use the mailing lists fine for people on the same domain as the Zimbra server.

Without milter and external users, you will get DKIM/SPF and DMARC failure, resulting in mails going to spam
